[package]
name = "rdevid-binding-c"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
rdevid = { path = "../../rdevid" }

[build-dependencies]
cbindgen = "0.29.0"
