[package]
name = "rdevid-binding-wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
rdevid = { path = "../../rdevid", features = ["wasm"] }

[lib]
crate-type = ["cdylib", "rlib"]
